#!/bin/bash
status=$(/usr/bin/acpi -b)
percent="$(echo $status | grep -o '[0-9]\{1,3\}%' | tr -d '%')"

if [[ $status == *'Discharging'* ]]; then
  if [[ $percent > 50 ]]; then
    echo " $percent%";
  elif [[ $percent > 25 ]]; then
    echo " $percent%";
  elif [[ $percent > 5 ]]; then
    echo " $percent%";
  else
    echo " $percent%";
  fi
elif [[ $status == *'Charging'* ]]; then
  echo "  $percent%";
elif [[ $status == *'Full'* ]]; then
  echo "  Full";
else
  echo "?  $percent%";
fi
